# narrativa.py - Diccionario de preguntas forenses
# Mapea cada rasgo interno del motor a una pregunta legible para el jugador.
PREGUNTAS = {
    "gafas": "¿El perfil criminológico indica el uso de anteojos?",
    "rubio": "¿Los testigos mencionan cabello claro o rubio en el sujeto?",
    "apartamento": "¿Hay indicios de que los crímenes se cometían en el domicilio del atacante?",
    "preservacion": "¿El modus operandi incluye la conservación grotesca de restos?",
    "canibalismo": "¿Hay evidencia forense de antropofagia (canibalismo)?",
    "siglo_20": "¿Los crímenes están documentados durante el siglo XX?",
    "estrangulacion": "¿El reporte médico indica estrangulación o asfixia mecánica?",
    "wisconsin": "¿El sujeto operaba en la jurisdicción del estado de Wisconsin?",
    "traje": "¿El asesino solía vestir de manera formal para inspirar confianza?",
    "carismatico": "¿El sospechoso poseía una personalidad engañosamente encantadora?",
    "volkswagen": "¿Hay reportes de un vehículo Volkswagen asociado a los crímenes?",
    "fuga": "¿Existe algún registro de fuga exitosa de una prisión?",
    "florida": "¿El rastro de sangre principal se encuentra en el estado de Florida?",
    "secuestro": "¿El modus operandi implicaba la privación ilegal de la libertad?",
    "mascara": "¿El atacante utilizaba una máscara o capucha en sus crímenes?",
    "cartas": "¿El sujeto se burlaba de las autoridades enviando cartas?",
    "simbolos": "¿El asesino dejaba símbolos crípticos o firmas visuales?",
    "criptogramas": "¿Los mensajes del sospechoso contenían códigos sin descifrar?",
    "california": "¿El área de operación principal fue en la costa oeste, en California?",
    "arma_de_fuego": "¿El arma homicida preferida era un arma de fuego?",
    "identidad_desconocida": "¿La verdadera identidad del atacante sigue siendo un misterio?",
    "payaso": "¿Hay una fijación documentada con disfraces o payasos?",
    "fiestas": "¿El sujeto solía organizar eventos o fiestas en su vecindario?",
    "sotano": "¿Se ocultaron restos humanos en los cimientos o sótano de su casa?",
    "pogo": "¿El perfil psicológico incluye una identidad alterna documentada?",
    "illinois": "¿La jurisdicción principal de los asesinatos fue en Illinois?",
    "enterrador": "¿El sospechoso trabajaba como contratista o en construcción?",
    "pentagrama": "¿Se encontraron pentagramas dibujados en las escenas del crimen?",
    "negro": "¿Los testigos afirman que vestía ropa oscura y atacaba de noche?",
    "dientes": "¿Existe algún reporte sobre anomalías dentales en el sospechoso?",
    "satanismo": "¿La escena mostraba evidencia de adoración o rituales satánicos?",
    "invasion_domestica": "¿El atacante irrumpía violentamente en el domicilio de sus víctimas?",
    "mujer": "¿El perfil criminológico apunta a una sospechosa femenina?",
    "carretera": "¿El modus operandi involucraba cazar a las víctimas en autopistas?",
    "pistola": "¿Utilizaba una pistola para someter y asesinar?",
    "robo": "¿El móvil secundario de los crímenes era el asalto o robo?",
    "lider": "¿Se sospecha que el sujeto actuaba como líder de un grupo?",
    "secta": "¿Hay indicios de actividad sectaria organizada?",
    "marca_frente": "¿El sospechoso tiene marcas distintivas en el rostro?",
    "familia": "¿El sujeto se refería a su grupo de seguidores como 'la familia'?",
    "autor_intelectual": "¿El sujeto ordenaba a otros matar en lugar de hacerlo él mismo?",
    "granjero": "¿El asesino vivía en un entorno rural o poseía una granja?",
    "piel": "¿El modus operandi incluía la mutilación para crear objetos con restos?",
    "madre": "¿El perfil psicológico indica una obsesión con su figura materna?",
    "profanador": "¿El reporte forense indica que profanaba tumbas locales?",
    "aislamiento": "¿Vivía en un aislamiento extremo, alejado de la sociedad?",
    "mutilacion": "¿Los cuerpos presentaban desmembramiento severo?",
    "cuerda": "¿Utilizaba cuerdas o ligaduras específicas como firma?",
    "iglesia": "¿El sospechoso tenía alguna conexión con instituciones religiosas?",
    "tecnico": "¿El sospechoso trabajaba como técnico o instalador de alarmas?",
    "kansas": "¿El terror se desató principalmente en la región de Kansas?",
    "anciano": "¿El sospechoso continuó su actividad criminal hasta la vejez?",
    "agujas": "¿El sujeto insertaba objetos extraños, como agujas, en su cuerpo?",
    "nueva_york": "¿Los homicidios tuvieron lugar en la zona de Nueva York?",
    "hotel": "¿El sujeto utilizaba un hotel o pensión como terreno de caza?",
    "castillo": "¿Se asoció al asesino con un edificio modificado con trampas?",
    "sombrero_copa": "¿Vestía a la usanza formal, incluyendo sombreros de copa?",
    "victoriano": "¿El sujeto encaja en el perfil de la época victoriana?",
    "chicago": "¿La serie de asesinatos ocurrió en la ciudad de Chicago?",
    "siglo_19": "¿Los eventos se desarrollaron a finales del siglo XIX?",
    "fraude": "¿El asesino también estaba involucrado en estafas de seguros?",
    "gas": "¿Utilizaba cámaras de asfixia rudimentarias mediante líneas de gas?",
    "ex_policia": "¿El perfil indica que el sospechoso tenía entrenamiento policial?",
    "adn": "¿El caso se resolvió décadas después gracias a pruebas de ADN?",
    "pasamontañas": "¿Se reportó el uso de un pasamontañas para ocultar su rostro?",
    "cuchillo": "¿El arma homicida principal era un arma blanca o cuchillo?",
    "londres": "¿Los crímenes aterrorizaron el área metropolitana de Londres?",
    "prostitutas": "¿Las víctimas pertenecían a grupos vulnerables en las calles?"
}